-- Generated by ERDone (SQL Server)
-- 2026-09-28T23:37:36.509Z

CREATE TABLE [Surveys] (
  [IdSurvey] INT NOT NULL,
  [IdCliente] INT NOT NULL,
  [IdProducto] INT NOT NULL,
  [IdFuente] INT NOT NULL,
  [IdClasificacion] INT NOT NULL,
  [Fecha] DATE NOT NULL,
  [Comentario] VARCHAR(60) NOT NULL,
  [PuntajeClasificacion] INT NOT NULL,
  CONSTRAINT [PK_Surveys] PRIMARY KEY ([IdSurvey])
);
GO

CREATE TABLE [Fuente de Datos] (
  [IdFuente] INT NOT NULL,
  [FechaCarga] DATE NOT NULL,
  [IdTipodeFuente] INT NOT NULL,
  CONSTRAINT [PK_Fuente de Datos] PRIMARY KEY ([IdFuente])
);
GO

CREATE TABLE [Clasificacion] (
  [IdClasificacion] INT NOT NULL,
  [NombreClasificacion] VARCHAR(60) NOT NULL,
  CONSTRAINT [PK_Clasificacion] PRIMARY KEY ([IdClasificacion])
);
GO

CREATE TABLE [Categoria] (
  [IdCategoria] INT NOT NULL,
  [NombreCategoria] VARCHAR(60) NOT NULL,
  CONSTRAINT [PK_Categoria] PRIMARY KEY ([IdCategoria])
);
GO

CREATE TABLE [Cliente] (
  [IdCliente] INT NOT NULL,
  [Nombre] VARCHAR(60) NOT NULL,
  [Email] VARCHAR(60) NOT NULL,
  CONSTRAINT [PK_Cliente] PRIMARY KEY ([IdCliente])
);
GO

CREATE TABLE [Producto] (
  [IdProducto] INT NOT NULL,
  [Nombre] VARCHAR(60) NOT NULL,
  [IdCategoria] INT NOT NULL,
  CONSTRAINT [PK_Producto] PRIMARY KEY ([IdProducto])
);
GO

CREATE TABLE [Social Comments] (
  [IdComentario] INT NOT NULL,
  [IdCliente] INT NOT NULL,
  [IdProducto] INT NOT NULL,
  [IdFuente] INT NOT NULL,
  [Fecha] DATE NOT NULL,
  [Comentario] VARCHAR(60) NOT NULL,
  CONSTRAINT [PK_Social Comments] PRIMARY KEY ([IdComentario])
);
GO

CREATE TABLE [Web Reviews] (
  [IdReview] INT NOT NULL,
  [IdCliente] INT NOT NULL,
  [IdProducto] INT NOT NULL,
  [Fecha] DATE NOT NULL,
  [Comentario] VARCHAR(60) NOT NULL,
  [Rating] INT NOT NULL,
  CONSTRAINT [PK_Web Reviews] PRIMARY KEY ([IdReview])
);
GO

CREATE TABLE [Tipo de fuente] (
  [IdTipodeFuente] INT NOT NULL,
  [NombreFuente] VARCHAR(MAX) NOT NULL,
  CONSTRAINT [PK_Tipo de fuente] PRIMARY KEY ([IdTipodeFuente])
);
GO

-- Foreign key constraints
ALTER TABLE [Surveys] ADD CONSTRAINT [FK_Surveys_IdCliente] FOREIGN KEY ([IdCliente]) REFERENCES [Cliente] ([IdCliente]);
GO
ALTER TABLE [Surveys] ADD CONSTRAINT [FK_Surveys_IdClasificacion] FOREIGN KEY ([IdClasificacion]) REFERENCES [Clasificacion] ([IdClasificacion]);
GO
ALTER TABLE [Surveys] ADD CONSTRAINT [FK_Surveys_IdProducto] FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([IdProducto]);
GO
ALTER TABLE [Surveys] ADD CONSTRAINT [FK_Surveys_IdFuente] FOREIGN KEY ([IdFuente]) REFERENCES [Fuente de Datos] ([IdFuente]);
GO
ALTER TABLE [Producto] ADD CONSTRAINT [FK_Producto_IdCategoria] FOREIGN KEY ([IdCategoria]) REFERENCES [Categoria] ([IdCategoria]);
GO
ALTER TABLE [Social Comments] ADD CONSTRAINT [FK_Social Comments_IdCliente] FOREIGN KEY ([IdCliente]) REFERENCES [Cliente] ([IdCliente]);
GO
ALTER TABLE [Social Comments] ADD CONSTRAINT [FK_Social Comments_IdProducto] FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([IdProducto]);
GO
ALTER TABLE [Social Comments] ADD CONSTRAINT [FK_Social Comments_IdFuente] FOREIGN KEY ([IdFuente]) REFERENCES [Fuente de Datos] ([IdFuente]);
GO
ALTER TABLE [Web Reviews] ADD CONSTRAINT [FK_Web Reviews_IdProducto] FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([IdProducto]);
GO
ALTER TABLE [Web Reviews] ADD CONSTRAINT [FK_Web Reviews_IdCliente] FOREIGN KEY ([IdCliente]) REFERENCES [Cliente] ([IdCliente]);
GO
ALTER TABLE [Tipo de fuente] ADD CONSTRAINT [FK_Tipo de fuente_IdTipodeFuente] FOREIGN KEY ([IdTipodeFuente]) REFERENCES [Fuente de Datos] ([IdTipodeFuente]);
GO

-- Indexes
CREATE INDEX [IX_Surveys_IdCliente] ON [Surveys] ([IdCliente]);
GO
CREATE INDEX [IX_Surveys_IdClasificacion] ON [Surveys] ([IdClasificacion]);
GO
CREATE INDEX [IX_Surveys_IdProducto] ON [Surveys] ([IdProducto]);
GO
CREATE INDEX [IX_Surveys_IdFuente] ON [Surveys] ([IdFuente]);
GO
CREATE INDEX [IX_Producto_IdCategoria] ON [Producto] ([IdCategoria]);
GO
CREATE INDEX [IX_Social Comments_IdCliente] ON [Social Comments] ([IdCliente]);
GO
CREATE INDEX [IX_Social Comments_IdProducto] ON [Social Comments] ([IdProducto]);
GO
CREATE INDEX [IX_Social Comments_IdFuente] ON [Social Comments] ([IdFuente]);
GO
CREATE INDEX [IX_Web Reviews_IdProducto] ON [Web Reviews] ([IdProducto]);
GO
CREATE INDEX [IX_Web Reviews_IdCliente] ON [Web Reviews] ([IdCliente]);
GO
