-- Generated by ERDone (PostgreSQL)
-- 2026-09-28T23:34:23.270Z

CREATE TABLE "Surveys" (
  "IdSurvey" INTEGER NOT NULL,
  "IdCliente" INTEGER NOT NULL,
  "IdProducto" INTEGER NOT NULL,
  "IdFuente" INTEGER NOT NULL,
  "IdClasificacion" INTEGER NOT NULL,
  "Fecha" DATE NOT NULL,
  "Comentario" VARCHAR(60) NOT NULL,
  "PuntajeClasificacion" INTEGER NOT NULL,
  CONSTRAINT "PK_Surveys" PRIMARY KEY ("IdSurvey")
);

CREATE TABLE "Fuente de Datos" (
  "IdFuente" INTEGER NOT NULL,
  "FechaCarga" DATE NOT NULL,
  "IdTipodeFuente" INTEGER NOT NULL
);

CREATE TABLE "Clasificacion" (
  "IdClasificacion" INTEGER NOT NULL,
  "NombreClasificacion" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Clasificacion" PRIMARY KEY ("IdClasificacion")
);

CREATE TABLE "Categoria" (
  "IdCategoria" INTEGER NOT NULL,
  "NombreCategoria" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Categoria" PRIMARY KEY ("IdCategoria")
);

CREATE TABLE "Cliente" (
  "IdCliente" INTEGER NOT NULL,
  "Nombre" VARCHAR(60) NOT NULL,
  "Email" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Cliente" PRIMARY KEY ("IdCliente")
);

CREATE TABLE "Producto" (
  "IdProducto" INTEGER NOT NULL,
  "Nombre" VARCHAR(60) NOT NULL,
  "IdCategoria" INTEGER NOT NULL,
  CONSTRAINT "PK_Producto" PRIMARY KEY ("IdProducto")
);

CREATE TABLE "Social Comments" (
  "IdComentario" INTEGER NOT NULL,
  "IdCliente" INTEGER NOT NULL,
  "IdProducto" INTEGER NOT NULL,
  "IdFuente" INTEGER NOT NULL,
  "Fecha" DATE NOT NULL,
  "Comentario" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Social Comments" PRIMARY KEY ("IdComentario")
);

CREATE TABLE "Web Reviews" (
  "IdReview" INTEGER NOT NULL,
  "IdCliente" INTEGER NOT NULL,
  "IdProducto" INTEGER NOT NULL,
  "Fecha" DATE NOT NULL,
  "Comentario" VARCHAR(60) NOT NULL,
  "Rating" INTEGER NOT NULL,
  CONSTRAINT "PK_Web Reviews" PRIMARY KEY ("IdReview")
);

CREATE TABLE "Tipo de fuente" (
  "IdTipodeFuente" INTEGER NOT NULL,
  "NombreFuente" TEXT NOT NULL,
  CONSTRAINT "PK_Tipo de fuente" PRIMARY KEY ("IdTipodeFuente")
);
