-- Generated by ERDone (PostgreSQL)
-- 2026-09-28T23:22:33.980Z

CREATE TABLE "Surveys" (
  "IdSurvey" INTEGER NOT NULL,
  "IdCliente" INTEGER NOT NULL,
  "IdProducto" INTEGER NOT NULL,
  "IdFuente" INTEGER NOT NULL,
  "IdClasificacion" INTEGER NOT NULL,
  "Fecha" DATE NOT NULL,
  "Comentario" VARCHAR(60) NOT NULL,
  "PuntajeClasificacion" INTEGER NOT NULL,
  CONSTRAINT "PK_Surveys" PRIMARY KEY ("IdSurvey")
);

CREATE TABLE "Fuente de Datos" (
  "IdFuente" INTEGER NOT NULL,
  "FechaCarga" DATE NOT NULL,
  "IdTipodeDato" INTEGER NOT NULL
);

CREATE TABLE "Clasificacion" (
  "IdClasificacion" INTEGER NOT NULL,
  "NombreClasificacion" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Clasificacion" PRIMARY KEY ("IdClasificacion")
);

CREATE TABLE "Categoria" (
  "IdCategoria" INTEGER NOT NULL,
  "NombreCategoria" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Categoria" PRIMARY KEY ("IdCategoria")
);

CREATE TABLE "Cliente" (
  "IdCliente" INTEGER NOT NULL,
  "Nombre" VARCHAR(60) NOT NULL,
  "Email" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Cliente" PRIMARY KEY ("IdCliente")
);
