-- Generated by ERDone (PostgreSQL)
-- 2026-09-28T23:36:02.554Z

CREATE TABLE "Surveys" (
  "IdSurvey" INTEGER NOT NULL,
  "IdCliente" INTEGER NOT NULL,
  "IdProducto" INTEGER NOT NULL,
  "IdFuente" INTEGER NOT NULL,
  "IdClasificacion" INTEGER NOT NULL,
  "Fecha" DATE NOT NULL,
  "Comentario" VARCHAR(60) NOT NULL,
  "PuntajeClasificacion" INTEGER NOT NULL,
  CONSTRAINT "PK_Surveys" PRIMARY KEY ("IdSurvey")
);

CREATE TABLE "Fuente de Datos" (
  "IdFuente" INTEGER NOT NULL,
  "FechaCarga" DATE NOT NULL,
  "IdTipodeFuente" INTEGER NOT NULL
);

CREATE TABLE "Clasificacion" (
  "IdClasificacion" INTEGER NOT NULL,
  "NombreClasificacion" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Clasificacion" PRIMARY KEY ("IdClasificacion")
);

CREATE TABLE "Categoria" (
  "IdCategoria" INTEGER NOT NULL,
  "NombreCategoria" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Categoria" PRIMARY KEY ("IdCategoria")
);

CREATE TABLE "Cliente" (
  "IdCliente" INTEGER NOT NULL,
  "Nombre" VARCHAR(60) NOT NULL,
  "Email" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Cliente" PRIMARY KEY ("IdCliente")
);

CREATE TABLE "Producto" (
  "IdProducto" INTEGER NOT NULL,
  "Nombre" VARCHAR(60) NOT NULL,
  "IdCategoria" INTEGER NOT NULL,
  CONSTRAINT "PK_Producto" PRIMARY KEY ("IdProducto")
);

CREATE TABLE "Social Comments" (
  "IdComentario" INTEGER NOT NULL,
  "IdCliente" INTEGER NOT NULL,
  "IdProducto" INTEGER NOT NULL,
  "IdFuente" INTEGER NOT NULL,
  "Fecha" DATE NOT NULL,
  "Comentario" VARCHAR(60) NOT NULL,
  CONSTRAINT "PK_Social Comments" PRIMARY KEY ("IdComentario")
);

CREATE TABLE "Web Reviews" (
  "IdReview" INTEGER NOT NULL,
  "IdCliente" INTEGER NOT NULL,
  "IdProducto" INTEGER NOT NULL,
  "Fecha" DATE NOT NULL,
  "Comentario" VARCHAR(60) NOT NULL,
  "Rating" INTEGER NOT NULL,
  CONSTRAINT "PK_Web Reviews" PRIMARY KEY ("IdReview")
);

CREATE TABLE "Tipo de fuente" (
  "IdTipodeFuente" INTEGER NOT NULL,
  "NombreFuente" TEXT NOT NULL,
  CONSTRAINT "PK_Tipo de fuente" PRIMARY KEY ("IdTipodeFuente")
);

-- Foreign key constraints
ALTER TABLE "Surveys" ADD CONSTRAINT "FK_Surveys_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES "Cliente" ("IdCliente");
ALTER TABLE "Surveys" ADD CONSTRAINT "FK_Surveys_IdClasificacion" FOREIGN KEY ("IdClasificacion") REFERENCES "Clasificacion" ("IdClasificacion");
ALTER TABLE "Surveys" ADD CONSTRAINT "FK_Surveys_IdProducto" FOREIGN KEY ("IdProducto") REFERENCES "Producto" ("IdProducto");
ALTER TABLE "Producto" ADD CONSTRAINT "FK_Producto_IdCategoria" FOREIGN KEY ("IdCategoria") REFERENCES "Categoria" ("IdCategoria");
ALTER TABLE "Social Comments" ADD CONSTRAINT "FK_Social Comments_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES "Cliente" ("IdCliente");
ALTER TABLE "Social Comments" ADD CONSTRAINT "FK_Social Comments_IdProducto" FOREIGN KEY ("IdProducto") REFERENCES "Producto" ("IdProducto");
ALTER TABLE "Web Reviews" ADD CONSTRAINT "FK_Web Reviews_IdProducto" FOREIGN KEY ("IdProducto") REFERENCES "Producto" ("IdProducto");
ALTER TABLE "Web Reviews" ADD CONSTRAINT "FK_Web Reviews_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES "Cliente" ("IdCliente");
ALTER TABLE "Tipo de fuente" ADD CONSTRAINT "FK_Tipo de fuente_IdTipodeFuente" FOREIGN KEY ("IdTipodeFuente") REFERENCES "Fuente de Datos" ("IdTipodeFuente");

-- Indexes
CREATE INDEX "IX_Surveys_IdCliente" ON "Surveys" ("IdCliente");
CREATE INDEX "IX_Surveys_IdClasificacion" ON "Surveys" ("IdClasificacion");
CREATE INDEX "IX_Surveys_IdProducto" ON "Surveys" ("IdProducto");
CREATE INDEX "IX_Producto_IdCategoria" ON "Producto" ("IdCategoria");
CREATE INDEX "IX_Social Comments_IdCliente" ON "Social Comments" ("IdCliente");
CREATE INDEX "IX_Social Comments_IdProducto" ON "Social Comments" ("IdProducto");
CREATE INDEX "IX_Web Reviews_IdProducto" ON "Web Reviews" ("IdProducto");
CREATE INDEX "IX_Web Reviews_IdCliente" ON "Web Reviews" ("IdCliente");
